services:
  db:
    image: "postgres:alpine"
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
  redis:
    image: "redis:alpine"
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sf_server
    restart: always
    env_file:
      - .env.local
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
      - redis
volumes:
  db_data:
  redis_data: